---
roles:
  - name: ahuffman.resolv
    src: git+http://172.17.0.1:3143/ansible-resolv.git
    version: 1.3.1
  - name: stackhpc.systemd_networkd
    src: git+http://172.17.0.1:3143/ansible-role-systemd-networkd.git
    version: v1.0.1
  - name: giovtorres.tuned
    src: git+http://172.17.0.1:3143/ansible-role-tuned.git
    version: 1.1.0
  - name: jriguera.configdrive
    src: git+http://172.17.0.1:3143/ansible-role-configdrive.git
    # There are no versioned releases of this role.
    version: 29871bf3279ef95fc8f7339b9abd13f869980750
  - name: MichaelRigart.interfaces
    src: git+http://172.17.0.1:3143/ansible-role-interfaces.git
    version: v1.13.1
  - name: mrlesmithjr.chrony
    src: git+http://172.17.0.1:3143/ansible-chrony.git
    version: v0.1.4
  - name: mrlesmithjr.manage-lvm
    src: git+http://172.17.0.1:3143/ansible-manage-lvm.git
    version: v0.2.6
  - name: mrlesmithjr.mdadm
    src: git+http://172.17.0.1:3143/ansible-mdadm.git
    version: v0.1.1
  - name: singleplatform-eng.users
    src: git+http://172.17.0.1:3143/ansible-users.git
    version: v1.2.5
  - name: stackhpc.dell-powerconnect-switch
    src: git+http://172.17.0.1:3143/ansible-role-dell-powerconnect-switch.git
    version: v1.1.0
  - name: stackhpc.drac
    src: git+http://172.17.0.1:3143/drac.git
    version: 1.1.6
  - name: stackhpc.drac-facts
    src: git+http://172.17.0.1:3143/drac-facts.git
    version: 1.0.0
  - name: stackhpc.grafana-conf
    src: git+http://172.17.0.1:3143/ansible-role-grafana-conf.git
    version: 1.1.1
  - name: stackhpc.libvirt-host
    src: git+http://172.17.0.1:3143/ansible-role-libvirt-host.git
    version: v1.8.3
  - name: stackhpc.libvirt-vm
    src: git+http://172.17.0.1:3143/ansible-role-libvirt-vm.git
    version: v1.14.2
  - name: stackhpc.luks
    src: git+http://172.17.0.1:3143/ansible-role-luks.git
    version: 0.4.2
  - name: stackhpc.mellanox-switch
    src: git+http://172.17.0.1:3143/ansible-role-mellanox-switch.git
    version: v1.0.0
  - name: stackhpc.os-images
    src: git+http://172.17.0.1:3143/ansible-role-os-images.git
    version: v1.10.7
  - name: stackhpc.os-ironic-state
    src: git+http://172.17.0.1:3143/ansible-role-os-ironic-state.git
    version: v1.3.1
  - name: stackhpc.os-networks
    src: git+http://172.17.0.1:3143/ansible-role-os-networks.git
    version: v1.5.3
  - name: stackhpc.os-openstackclient
    src: git+http://172.17.0.1:3143/ansible-role-os-openstackclient.git
    version: v1.4.1
  - name: stackhpc.os_openstacksdk
    src: git+http://172.17.0.1:3143/ansible-role-os-openstacksdk.git
    version: v1.0.1
  - name: stackhpc.timezone
    src: git+http://172.17.0.1:3143/ansible-timezone.git
    version: 1.2.1
